# Generated by Django 4.2.3 on 2023-07-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
    ]
