# Generated by Django 4.2.3 on 2023-07-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_f_name_user_name_remove_user_l_name'),
    ]

    operations = [
    ]
