# Generated by Django 4.2.3 on 2023-07-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230720_0951'),
    ]

    operations = [
    ]
