# Generated by Django 4.2.3 on 2023-07-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230720_0959'),
    ]

    operations = [
    ]
